spring:
  profiles:
    active: local

server:
  port: 8081

---
spring:
  profiles: local

app:
  api:
    member:
      scheme: http
      host: localhost
      port: 8080

---
spring:
  profiles: dev

app:
  api:
    member:
      scheme: http
      host: localhost
      port: 8080