spring:
  profiles:
    active: local

server:
  port: 80

---
spring:
  profiles: local
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/static/

app:
  api:
    member:
      scheme: http
      host: localhost
      port: 8080

---
spring:
  profiles: dev
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/static/

app:
  api:
    member:
      scheme: http
      host: localhost
      port: 8080